/*
 * Anton dela Cruz
 * GUIquiz.java
 * This program prompts users to take the quiz, and will display the users' performance based on the amount of correct answers.
 * October 15, 2018
 */

/**
 *
 * @author antde
 */

public class GUIquiz extends javax.swing.JFrame {
    
    String ans1, ans2, ans3, ans4, ans5;
    int correctans = 0, wrongans = 0;
    double percentage;
   
    
    public GUIquiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        q1 = new javax.swing.JLabel();
        q1A = new javax.swing.JLabel();
        q1B = new javax.swing.JLabel();
        q1C = new javax.swing.JLabel();
        q2 = new javax.swing.JLabel();
        q2A = new javax.swing.JLabel();
        q2B = new javax.swing.JLabel();
        q2C = new javax.swing.JLabel();
        q3 = new javax.swing.JLabel();
        q3A = new javax.swing.JLabel();
        q3C = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        q4 = new javax.swing.JLabel();
        q4A = new javax.swing.JLabel();
        q4B = new javax.swing.JLabel();
        q4C = new javax.swing.JLabel();
        q5 = new javax.swing.JLabel();
        q5A = new javax.swing.JLabel();
        q5B = new javax.swing.JLabel();
        q5C = new javax.swing.JLabel();
        ansBox1 = new javax.swing.JTextField();
        ansBox2 = new javax.swing.JTextField();
        ansBox3 = new javax.swing.JTextField();
        ansBox4 = new javax.swing.JTextField();
        ansBox5 = new javax.swing.JTextField();
        correctlbl = new javax.swing.JLabel();
        wronglbll = new javax.swing.JLabel();
        percentagelbl = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        amtcorrect = new javax.swing.JLabel();
        amtincorrect = new javax.swing.JLabel();
        amtPercent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        title.setForeground(new java.awt.Color(204, 0, 0));
        title.setText("Comic Knowledge Quiz");

        q1.setText("1. What is Spider-Man's secret identity?");

        q1A.setText("A. Tim Drake");

        q1B.setText("B. Peter Parker");

        q1C.setText("C. Wade Wilson");

        q2.setText("2. What is Superman's weakness?");

        q2A.setText("A. Kryptonite");

        q2B.setText("B. Fire");

        q2C.setText("C. Broccoli");

        q3.setText("3. Which Robin became Red Hood?");

        q3A.setText("A. Jason Todd");

        q3C.setText("B. Damian Wayne");

        jLabel13.setText("C. Dick Grayson");

        q4.setText("4. What is the Flash's secret identity?");

        q4A.setText("A. Cisco Ramon");

        q4B.setText("B. Barry Allen");

        q4C.setText("C. Clark Kent");

        q5.setText("5. Who \"dies\" in Avengers: Infinity War?");

        q5A.setText("A. Captain America");

        q5B.setText("B. Thor");

        q5C.setText("C. Starlord");

        ansBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansBox1ActionPerformed(evt);
            }
        });

        ansBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansBox4ActionPerformed(evt);
            }
        });

        correctlbl.setText("Correctly Answered:");

        wronglbll.setText("Incorrect Answers:");

        percentagelbl.setText("Percentage of correct answers:");

        button.setText("Calculate Performance");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        amtcorrect.setText("0");

        amtincorrect.setText("0");

        amtPercent.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1)
                            .addComponent(q2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q2A)
                                    .addComponent(q3A)
                                    .addComponent(q1A)
                                    .addComponent(q1C)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q1B)
                                        .addGap(39, 39, 39)
                                        .addComponent(ansBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(q2C)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q3C)
                                            .addComponent(jLabel13))
                                        .addGap(26, 26, 26)
                                        .addComponent(ansBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q2B)
                                        .addGap(82, 82, 82)
                                        .addComponent(ansBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(q4B)
                                                        .addGap(39, 39, 39)
                                                        .addComponent(ansBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(button))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(amtincorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(amtcorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(108, 108, 108))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(q4C)
                                                    .addComponent(q4A)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(414, 414, 414)
                                                        .addComponent(amtPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(78, 78, 78))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(q4)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(q5)
                                                    .addGap(81, 81, 81)
                                                    .addComponent(correctlbl))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(q5B)
                                                            .addGap(70, 70, 70)
                                                            .addComponent(ansBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(142, 142, 142)
                                                            .addComponent(wronglbll))
                                                        .addComponent(q5A)
                                                        .addComponent(q5C))))
                                            .addComponent(percentagelbl))
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1)
                    .addComponent(q4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1A)
                    .addComponent(q4A))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1B)
                    .addComponent(q4B)
                    .addComponent(ansBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1C)
                    .addComponent(q4C))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2)
                    .addComponent(q5)
                    .addComponent(correctlbl)
                    .addComponent(amtcorrect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2A)
                    .addComponent(q5A))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wronglbll)
                    .addComponent(amtincorrect)
                    .addComponent(q2B)
                    .addComponent(ansBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q5B)
                    .addComponent(ansBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2C)
                    .addComponent(q5C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amtPercent)
                    .addComponent(percentagelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3C)
                    .addComponent(ansBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ansBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansBox1ActionPerformed
        
    }//GEN-LAST:event_ansBox1ActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        
        ans1 = ansBox1.getText();
        ans2 = ansBox2.getText();
        ans3 = ansBox3.getText();
        ans4 = ansBox4.getText();
        ans5 = ansBox5.getText();
        
        if ((ans1.equals("B"))||(ans1.equals("b")) ) {
            correctans = correctans + 1;
        } else {
            wrongans = wrongans + 1;
        }
        
        if ((ans2.equals("A"))||(ans2.equals("a")) ) {
            correctans = correctans + 1;
        } else {
            wrongans = wrongans + 1;
        }
        
        if ((ans3.equals("A"))||(ans3.equals("a")) ) {
            correctans = correctans + 1;
        } else {
            wrongans = wrongans + 1;
        }
        
        if ((ans4.equals("B"))||(ans4.equals("b")) ) {
            correctans = correctans + 1;
        } else {
            wrongans = wrongans + 1;
        }
        
        if ((ans5.equals("C"))||(ans5.equals("c")) ) {
            correctans = correctans + 1;
        } else {
            wrongans = wrongans + 1;
        }
        if (correctans == 0) {
            percentage = 0;    
        }
        if (correctans == 1) {
            percentage = 20;    
        }
        if (correctans == 2) {
            percentage = 40;    
        }
        if (correctans == 3) {
            percentage = 60;    
        }
        if (correctans == 4) {
            percentage = 80;    
        }
        if (correctans == 5) {
            percentage = 100;    
        }
        
        amtcorrect.setText("" + correctans);
        
        amtincorrect.setText("" + wrongans);
        
        amtPercent.setText("" + percentage + "%");
           
    }//GEN-LAST:event_buttonActionPerformed

    private void ansBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIquiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIquiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIquiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIquiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIquiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amtPercent;
    private javax.swing.JLabel amtcorrect;
    private javax.swing.JLabel amtincorrect;
    private javax.swing.JTextField ansBox1;
    private javax.swing.JTextField ansBox2;
    private javax.swing.JTextField ansBox3;
    private javax.swing.JTextField ansBox4;
    private javax.swing.JTextField ansBox5;
    private javax.swing.JButton button;
    private javax.swing.JLabel correctlbl;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel percentagelbl;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q1A;
    private javax.swing.JLabel q1B;
    private javax.swing.JLabel q1C;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q2A;
    private javax.swing.JLabel q2B;
    private javax.swing.JLabel q2C;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q3A;
    private javax.swing.JLabel q3C;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q4A;
    private javax.swing.JLabel q4B;
    private javax.swing.JLabel q4C;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel q5A;
    private javax.swing.JLabel q5B;
    private javax.swing.JLabel q5C;
    private javax.swing.JLabel title;
    private javax.swing.JLabel wronglbll;
    // End of variables declaration//GEN-END:variables
}
